### ISSUE TITLE
"incorrect number of dimensions"

### ISSUE THREAD

**Issue by taiwoakinyemi** [asheshrambachan/HonestDiD#10]
Hi, 
While trying to create sensitivity results, I encountered an Error in {: task 1 failed - "incorrect number of dimensions."
Please can you take a look? I have not been able to find the root error and resolve it. The code line I am running is below

ghana_DeltaSD_RobustResults = createSensitivityResults(betahat = m1.plm_EventStudy$betahat, 
+                                                        sigma = m1.plm_EventStudy$sigma,
+                                                        numPrePeriods = ghana_numPrePeriods, 
+                                                        numPostPeriods = ghana_numPostPeriods,
+                                                        l_vec = ghana_l_vec, 
+                                                        Mvec = seq(from = 0, to = 0.04, by = 0.005))

**Comment by asheshrambachan** [comment]
Could you provide some more information about each of the inputs that you are passing to the `createSensitivityResults()` function? E.g., what is the dimension of `betahat`, `sigma` and `ghana_l_vec`? What are the values of `numPrePeriods` and `numPostPeriods`?

**Comment by taiwoakinyemi** [comment]
Thanks a lot for the prompt response.
I was using plm before, but I realized that coefIndex is empty.
Later I used lfe, and everything looked okay until I got to creating sensitivity results again, and I got "Error in {: task 1 failed - "non-conformable arguments." I saw a similar problem on the forum, which required including all the periods to resolve the error. However, I am using all the post and pre-periods. Please help. I have included a screenshot of some of the input variables.
![image](https://user-images.githubusercontent.com/57067445/153489094-9f05a2a7-5c4f-40f2-b15b-565186946b1a.png)
![image](https://user-images.githubusercontent.com/57067445/153489918-d36009ae-a4c6-44ab-bbd8-b30c1d2c63d5.png)
![image](https://user-images.githubusercontent.com/57067445/153489885-32e9b7a8-3427-4d6b-aacc-1738f71900f5.png)

**Comment by taiwoakinyemi** [comment]
I have figured out the problem, it has been resolved.
