### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by salem043** [asheshrambachan/HonestDiD#11]
Greetings. I am having trouble installing HonestDID using the instructions provided in the vignette. This is odd, since I had no issues installing last summer on my old laptop. I'm using a Windows OS with the most recent version of R Studio.

**Comment by asheshrambachan** [comment]
@salem043 Could you provide a screenshot of the installation command you're running and the error that's being returned?

**Comment by salem043** [comment]
Hi @asheshrambachan, thank you for offering to help. I updated the version of R and fully quit and relaunched. That did the trick. I'm sorry again about the bother!

**Comment by asheshrambachan** [comment]
No problem! And absolutely no need to apologize -- I'm glad it was fixed :)
