### ISSUE TITLE
What's the convention for indices that are not specified?

### ISSUE THREAD

**Issue by amrods** [asheshrambachan/HonestDiD#12]
In the paper you index beta and delta with negative indices for pre-treatment periods, and with positive indices for post-treatment periods. So, when constructing Delta^{SD}(M) for example, which includes expressions with delta_{t-1}, and delta_{t+1}, what is the convention for indices that are not defined? ie, how do I interpret expressions like delta_0, delta_(upperT+1), or delta_{lowerT-1}?

**Comment by asheshrambachan** [comment]
The number of pre-periods (lowerT) and number of post-periods (upperT) are given by the user/application. So, in Section 2.4 of the [draft](https://asheshrambachan.github.io/assets/files/hpt-draft.pdf), we define delta = (deltapre, deltapost) with delta_0 normalized to zero.

**Comment by amrods** [comment]
I'm just skipping restrictions that involve periods outside [lowerT, upperT].
