### ISSUE TITLE
A problem when i run command HonestDiD::createSensitivityResults_relativeMagnitudes

### ISSUE THREAD

**Issue by zkzhu-pro** [asheshrambachan/HonestDiD#16]
Thank you for creating this tool.
I need your help.
An error occurred when I run the R  command from the example:
(
**delta_rm_results <- 
HonestDiD::createSensitivityResults_relativeMagnitudes(
                                    betahat = betahat, #coefficients
                                    sigma = sigma, #covariance matrix
                                    numPrePeriods = 5, #num. of pre-treatment coefs
                                    numPostPeriods = 2, #num. of post-treatment coefs
                                    Mbarvec = seq(0.5,2,by=0.5) #values of Mbar
                                    )

delta_rm_results**
)
then console  show the below error
error in no package with the name 'Rglpk' exists.
how to deal with this problem, thanks!

**Comment by asheshrambachan** [comment]
Try installing the R package `Rglpk` using the command `install.packages("Rglpk")`

**Comment by zkzhu-pro** [comment]
> Try installing the R package `Rglpk` using the command `install.packages("Rglpk")`

The problem has been solved. Thank you for your help
