### ISSUE TITLE
A problem when i run command HonestDiD::createSensitivityResults_relativeMagnitudes

### ISSUE THREAD

**Issue by GustavFlorinAagren** [asheshrambachan/HonestDiD#18]
Thank you for creating this tool. It sure looks interesting and is something I would like to use for an upcoming project!
I need your help though

An error occurred when I run the R command from the example:

delta_rm_results <-
HonestDiD::createSensitivityResults_relativeMagnitudes(
betahat = betahat, #coefficients
sigma = sigma, #covariance matrix
numPrePeriods = 5, #num. of pre-treatment coefs
numPostPeriods = 2, #num. of post-treatment coefs
Mbarvec = seq(0.5,2,by=0.5) #values of Mbar
)

Then the console starts a procedure that seems to never stop. And when I stop it, it tells me there are more than 50 warning messages. Taking a look at these with warnings() two warnings are repeated over and over again. These:
Warning messages:
1: In seq_len(length.out - 2L) * (del/n1) :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.

2: In from + seq_len(length.out - 2L) * (del/n1) :
  Recycling array of length 1 in array-vector arithmetic is deprecated.
  Use c() or as.vector() instead

3: In seq_len(length.out - 2L) * (del/n1) :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.

4: In from + seq_len(length.out - 2L) * (del/n1) :
  Recycling array of length 1 in array-vector arithmetic is deprecated.
  Use c() or as.vector() instead.

And the rest are all the same.

How should I deal with this?

**Comment by jonathandroth** [comment]
How long did you let it run for?

Can you try setting gridPoints = 10 (instead of the default 1000) to see if
it runs?

**Comment by GustavFlorinAagren** [comment]
This worked. Though, when changing the gridPoints, I didn't get the same results as you show in the example. The closer I go to gridPoints=1000, the more the results look like yours. 
Interestingly, when I set the gridPoints back to 1000 the computation was completed much much faster than when I tried it the first time.
Thanks for helping me solve this! Now the whole example runs smoothly. Fantastic!

**Comment by jonathandroth** [comment]
The confidence interval is based on a discrete approximation using a
discrete number of grid points, so it's not surprising that it's not very
accurate if you only use 10. That is very strange that specifying the
default number of grid points changes the runtime, but I'm glad to hear
that it worked!
