### ISSUE TITLE
Query about CIs under different values of Mbar

### ISSUE THREAD

**Issue by Katebellis** [asheshrambachan/HonestDiD#19]
Hello,

Many thanks in advance if you're able to help at all. I've been playing around with the example data and performing the sensitivity analysis based on relative magnitudes in the staggered DiD case (using the function created by Pedro Sant'Anna) and have a query regarding the resulting confidence intervals. 

When I use a smaller increment between values of Mbar (e.g. Mbarvec = seq(from = 0.1, to = 1, by = 0.1)), some of the confidence intervals are identical for adjacent Mbar values. Would this just be a consequence of the precision of the code? 

Also, for very small values of Mbar (e.g. less than 0.3) the resulting confidence intervals are actually narrower than the original CI which does not seem intuitive to me. I wonder if this due to being close to Mbar=0 which is "not really allowed" (https://github.com/pedrohcgs/CS_RR) and thus we shouldn't use very small values of Mbar? 

Both of these findings also occurred when I implemented the methods on my own data. 

Thanks a lot!

**Comment by jonathandroth** [comment]
Hi Kate,

When did you download the function from Pedro's website? There was
unfortunately a bug with the original code that he wrote that caused some
weird results sometimes, but we fixed this a month or two ago.

That said, it's possible that this behavior is not a bug. The honestDiD
package creates a confidence interval by testing a discrete number of
points, and then collecting the points where a test doesn't reject into a
CI. So for very small changes in M, it is possible that the CI doesn't
change at the discrete points. The imprecision from the discrete grid can
also lead the CI for M~=0 to be smaller than the original CI. If you'd
like, you can increase the number of grid points used with the option
numGridPoints -- the default is 1000, but things will be more accurate, but
the command will be slower, if you increase it.

Best,
Jon

**Comment by Katebellis** [comment]
Hi Jon,

Thank you very much for your help, increasing the grid points has solved both issues.

All the best,
Kate

**Comment by jonathandroth** [comment]
Fantastic - glad to hear!
