### ISSUE TITLE
HonestDiD::createSensitivityPlot_relativeMagnitudes and unused filter

### ISSUE THREAD

**Issue by dschwartzman** [asheshrambachan/HonestDiD#20]
Thank you for both the theoretical contributions and the package!

I am having an issue with the createSensitivityPlot_relativeMagnitudes and createSensitivityPlot  functions. 

I am able to produce delta_rm_results and originalResults normally. However, when I do the following command:

HonestDiD::createSensitivityPlot_relativeMagnitudes(delta_rm_results, originalResults)

I get the error message:

Error in filter(., Mbar <= maxMbar) : unused argument (Mbar <= maxMbar)

Any guidance on this kind of issue? I was able to use the command without issue for about half a day and then this error appeared. I have tried re-loading the environment and re-installing the package.

**Comment by jonathandroth** [comment]
Hi,

Thanks very much for your email! It looks to me like in the
createSensitivityPlot_relativeMagnitudes(), the call to the filter()
function did not explicitly say dplyr::filter(). My guess is that this
worked for you until you loaded a different package with a filter()
function that behaves differently from the dplyr one. I have just pushed an
update that makes explicit the dplyr call. Can you reinstall the package
from github, restart R, and let me know if that works?

@Ashesh Rambachan ***@***.***>  we (or an RA) should go
through the package and make sure that all function calls are explicit
about the package.

Best,
Jon

**Comment by dschwartzman** [comment]
Yes, this resolved the issue. Thank you for your help!

**Comment by jonathandroth** [comment]
Glad to hear!

**Comment by mcaceresb** [comment]
@jonathandroth FYI #22 should also allow closing this issue.
