### ISSUE TITLE
Package dependencies and package conflicts

### ISSUE THREAD

**Issue by thameath** [asheshrambachan/HonestDiD#21]
You have already partially addressed this in a [previous issue](https://github.com/asheshrambachan/HonestDiD/issues/20#issuecomment-1412441027), but the way the current package dependencies are set up can cause conflicts depending on the other packages loaded into the environment, or even the order that those packages are loaded into the environment.  It is also making it difficult to install on some of our cluster computing environments.

There are a couple small changes that could be made to resolve 90% of these issues:

1. Move most of the packages listed in the DESCRIPTION file from `Depends:` to `Imports:`.  Depends forces all those packages to be loaded into the environment at the same time as your package, which is usually not necessary.  It's often sufficient to just have them available via explicit call (see next suggestion).

2. Make all the calls to external functions explicit, `package::function()` rather than just `function()`.  This will be necessary for packages listed in `Imports`, as they will not be natively loaded into the environment unlike the `Depends` packages.

3. Replace `tidyverse` in your dependencies list with the component packages. You currently include `tidyverse` in your `Depends` list, but `tidyverse` is a wrapper around multiple packages to allow for quicker loading.   It is currently unclear which of the underlying packages nor which versions are needed.

**Comment by jonathandroth** [comment]
Thanks for the feedback! 

I agree all of this should be implemented when we have the time. @mcaceresb -- would you be able to start on this when you finish with the stata-staggered implementation?

**Comment by mcaceresb** [comment]
@jonathandroth I believe I got all the dependencies (except for `ggplot`, which I left as it was). See #22
