### ISSUE TITLE
Options in `honest_did.AGGTEobj`

### ISSUE THREAD

**Issue by mcaceresb** [asheshrambachan/HonestDiD#27]
In the README, `honest_did` passes some options but not others:

- `Mvec` is captured but not passed along. `Mbarvec` is captured and passed.
- `gridPoints` is captured and not passed. It's further hard-coded to 100 with `relative_magnitude`
- `grid.ub` and `grid.lb` are both captured and not passed.
- Additional options are allowed via `...` but `...` is not passed to any function.

It strikes me that you don't need to capture most options and can just pass down `...`. Then for cases where the syntax is slightly different you can capture both elements but pass both user options (e.g. `Mvec` and `Mbarvec`); and for cases where you want a slightly different default you can re-define the option unless the user has specified it. LMK if this is the right way to think about it or if the README is correct and I misunderstood the intent.

**Comment by jonathandroth** [comment]
All these points look valid to me. (Pedro and I cobbled together this fn pretty quickly). I agree with your suggestions. Can you implement or do you need more info?
