### ISSUE TITLE
Warning for sigma that is not positive semi-definite

### ISSUE THREAD

**Issue by jonathandroth** [asheshrambachan/HonestDiD#36]
@mcaceresb when you have RA time in the fall, can you add a check for whether sigma is positive semi-definite and if not, throw a warning?

Providing HonestDID with a non-semi-definite Sigma led to some weird error messages, per the email we received from a student.

**Comment by mcaceresb** [comment]
@jonathandroth Sigma is also symmetric so I can just check the eigenvalues, right? The simple version is fairly quick to code. See PR #37.

**Comment by jonathandroth** [comment]
Well, it *should* be symmetric but I guess we can check that too.

If the smallest eigenvalue is very small (e.g. from numerical precision
errors), then things *might* run okay since we only run into problems if
gamma' Sigma gamma <= 0. So maybe a warning is okay? Don't have a strong
opinion.

On the topic of checks, do we currently check that betahat, sigma, and
l_vec all have conformable dimensions?

**Comment by mcaceresb** [comment]
@jonathandroth 

> Well, it *should* be symmetric but I guess we can check that too. If the smallest eigenvalue is very small (e.g. from numerical precision errors), then things *might* run okay since we only run into problems if gamma' Sigma gamma <= 0. So maybe a warning is okay? Don't have a strong opinion.

How about

- Stop if not symmetric, 
- Warn if not PSD or if any eigenvalue close to 0

> On the topic of checks, do we currently check that betahat, sigma, and l_vec all have conformable dimensions?

Not sure; will have a look.

**Comment by mcaceresb** [comment]
@jonathandroth Added in #39
