### ISSUE TITLE
Robust CIs narrower than original CIs with large number of pre-treatment periods

### ISSUE THREAD

**Issue by Katebellis** [asheshrambachan/HonestDiD#38]
Good morning,

I'm not sure if my previous issue sent properly so apologies if this is a duplicate. I'm in a staggered DiD setting with data available in 22 periods before treatment, and then staggered roll-out of treatment over the following 11 periods so e=-34 to e=11 in the event study setup.  

When using honestDiD with all pre-periods, a lot of the robust CIs for M=0 (under smoothness restriction) are  narrower than the original CIs. The issue remains when increasing the number of gridpoints. However, when I restrict the number of pre-periods in the event study (e.g. min_e = -6) after running Callaway and Sant'Anna's approach, the robust CIs are then wider than the originals. Should the number of pre-periods in the event study be restricted in this case or would the robust CIs using all periods still be valid?

Many thanks,
Kate

**Comment by jonathandroth** [comment]
Hi Kate,

M=0 with a smoothness restriction corresponds to a model with a linear
trend. It is possible for the CI for the model with the linear trend to be
tighter than the original CI, particularly if you have many periods to
estimate the slope. So I don't think the pattern you described is
necessarily a problem per se.

J

**Comment by Katebellis** [comment]
Hi Jon,

That's great, thanks for clarifying so quickly.

Best, 
Kate
