### ISSUE TITLE
Warning in install.packages: package ‘HonestDiD’ is not available for this version of R

### ISSUE THREAD

**Issue by Hanh7** [asheshrambachan/HonestDiD#43]
Hello, 
Thanks for creating this DID package, a nice paper as well.

I am trying to install your package and there is a warning saying "package ‘HonestDiD’ is not available for this version of R".
Which version of R can run your package?
Please see the photo for more info.

<img width="813" alt="Screen Shot 2023-09-12 at 10 37 30 PM" src="https://github.com/asheshrambachan/HonestDiD/assets/68261868/96748210-1f7d-4e3f-8a6b-1aac85f4257b">

**Comment by jonathandroth** [comment]
Hi, the package is not currently on CRAN (although hopefully will be soon),
so you cannot use install.packages. Please follow the instructions for
using install_github here
<https://github.com/asheshrambachan/HonestDiD#package-installation> and let
us know if that works.

J

**Comment by Hanh7** [comment]
Thanks for your quick reply. It works.

**Comment by jonathandroth** [comment]
Great!
