### ISSUE TITLE
Error when running sensitivity analysis with honest did

### ISSUE THREAD

**Issue by Hanh7** [asheshrambachan/HonestDiD#45]
Hello there, 

I am trying to apply the honestdid function to my dataset. However, these is an error: Error in base::matrix(0, nrow = size, ncol = 1): invalid 'nrow' value (< 0)". I showed detail of the error and it said "nrow = -5".
I tried to extract each metric of the result, such as beta, sigma (V), but I can't found where the error came from.

Any hints are valuable to me!

```R
> **#compute event study**
> cs_nevertreat <- did::att_gt(yname = "xxx",
+                           tname = "year",
+                           idname = "id", 
+                           gname = "y1", 
+                           data = df,
+                           control_group = "nevertreated",
+                           base_period = "universal")
> cs_es_nevertreat<- aggte(cs_nevertreat, type = "dynamic",
+                      min_e = -10, max_e = 8)
>**#sensitivity analysis**
> sensitivity_results <-
+   honest_did(cs_es_nevertreat,
+              e=0,
+              type="relative_magnitude")
**Error in base::matrix(0, nrow = size, ncol = 1) :
invalid 'nrow' value (< 0)**
> **#test code extract sigma, beta, tVec**
> es_nevertreat <- cs_es_nevertreat$inf.function$dynamic.inf.func.e
> n <- nrow(es_never)
Error: object 'es_never' not found
> n <- nrow(es_nevertreat)
> n
[1] 707
> V <- t(es_nevertreat) %*% es_nevertreat / n / n
> nrow(V)
[1] 10
> ncol(V)
[1] 10
> tVec <- cs_es_nevertreat$egt
> beta_es <- cs_es_nevertreat$att.egt
> data.frame(tVec,beta_es)
 ```

**Comment by jonathandroth** [comment]
Can you please provide a minimal working example that we can try to use to reproduce the error, either by sharing the data that you used or a synthetic dataset with similar structure that reproduces the error?

**Comment by Hanh7** [comment]
Hello, 
Sorry for my late reply. I put my dataset and description in this folder: https://drive.google.com/drive/folders/19tmsg6HR2k6xC7omqJkTV7lQ48PuBTwC?usp=drive_link

Could you kindly send me a request so that I can share to only you?

**Comment by jonathandroth** [comment]
@mcaceresb when you have RA time, can you look into this please?

**Comment by mcaceresb** [comment]
@jonathandroth @Hanh7 I can't download the example. I might not need it

- It seems the error is from this line: `basisVector(index=(e+1),size=npost)`
- `e <- 0`,`npost <- nperiods - npre`, `nperiods <- nrow(V)` and `npre <- sum(1*(es$egt < -1))`
- `es <- cs_es_nevertreat` 
- `V` is based on `es$inf.function$dynamic.inf.func.e` and `referencePeriodIndex <- which(es$egt == -1)`

So it seems there's two objects to analyze. What is

```R
es <- cs_es_nevertreat
dim(crossprod(es$inf.function$dynamic.inf.func.e))
es$egt
```

? My guess is that there's an issue with the `egt` vector.

**Comment by Hanh7** [comment]
Dear @mcaceresb,
 
I am still working on this.
I extracted egt, and this is it: 
<img width="307" alt="image" src="https://github.com/asheshrambachan/HonestDiD/assets/68261868/f2759cbf-30b4-42c0-9040-ab60de7d01ea">

Is it what it should look like?
Or should I fix the bug in the code of the function honest_did? I am using the code in your example, because my dataset seems to have the same structure with your example. Perhaps I incorrectly transform my dataset; it is not the same as yours?! 

By the way, I have made my dataset opened access, if you have time, could you kindly take a look?
https://drive.google.com/drive/folders/19tmsg6HR2k6xC7omqJkTV7lQ48PuBTwC

**Comment by mcaceresb** [comment]
@Hanh7 I don't think it's necessary. The issue appears to be that the reference period is hard-coded to -1 in `honest_did`.

You can change it to `-2` (I presume) for your use case, divide egt by 2, or copy the updated function from [here](https://github.com/mcaceresb/HonestDiD/blob/68f79fb56057ff547c2261de4c3e9f75aaf70f53/R/honest_did.R) and pass on the right reference period.

If there's still an issue I'll have a look at the data. LMK.

**Comment by Hanh7** [comment]
Many thanks for your quick reply. I'll try again.

**Comment by Hanh7** [comment]
Hello, 

May I ask about the meaning of Mbar mentioned in your Honest approach paper?  

I understand that Mbar as "_**The horizontal axis M shows our restriction on violations, i.e. the fraction of the maximum violations in post-treatment periods and the maximum violations in pre-treatment periods**_".

Please correct me if I am wrong.

**Comment by jonathandroth** [comment]
I would have said something like "the restriction that the magnitude of the
post-treament violations of parallel trends is no more than M times the
largest pre-treatment violation" or something like that.

**Comment by Hanh7** [comment]
Yes. I get the idea. Thank you.

**Comment by mcaceresb** [comment]
@Hanh7 We decided to throw an error if the time vector is not coded to be consecutive and have -1 as the reference period. So in this case you'd have to re-code it yourself before using HonestDiD. Cheers.
