### ISSUE TITLE
Hitting the upper bound?

### ISSUE THREAD

**Issue by elsavoytas** [asheshrambachan/HonestDiD#52]
Hello! Thank you for the package and for your help!

I'm using the did package and conducting sensitivity analysis with the [honest_did auxiliary function](https://github.com/pedrohcgs/CS_RR).

At some level of $\bar{M}$, the confidence intervals stop increasing, perhaps because they've reached the plot's upper/lower bound.

Here is the code used to produce the result, with period 7 as an example:
``` 
att2 <- att_gt(yname = "vote",
               tname = "time.id",
               idname = "ID",
               gname = "firstrep",
               xformla = ~age + female,
               data = panel.df,
               base_period = "universal",
               control_group = "notyettreated") 

es2 <- aggte(att2, type = "dynamic", na.rm = T, min_e = -12, max_e = 12)

sensitivityresults7 <- honest_did(es = es2, 
                   e = 7,
                   type="relative_magnitude")

sensitivityresults7$robust_ci <- sensitivityresults7$robust_ci[-1,]

createSensitivityPlot_relativeMagnitudes(sensitivityresults7$robust_ci,
                                                    sensitivityresults7$orig_ci)
```
The output is:

![image](https://github.com/asheshrambachan/HonestDiD/assets/32146369/bbb83970-b562-4b49-9106-0adae7a583c6)

The data can be found at: https://drive.google.com/drive/folders/1N5HEWIIZSX_EgKzrmX9R9hzcn5fE5zyq?usp=sharing

Do you have a suggestion to expand the bounds using this approach?

Thank you!!

**Comment by jonathandroth** [comment]
Have you tried e.g.:

honest_did(es = es2,
                   e = 7,
                   type="relative_magnitude",

grid.ub = 3)


if you want to make the grid ub 3

**Comment by elsavoytas** [comment]
Awesome! Thank you! That helped!
```
sensitivityresults7 <- honest_did(es = es2, 
                   e = 7,
                   type="relative_magnitude", grid.ub = 3, grid.lb = -1.5)

sensitivityresults7$robust_ci <- sensitivityresults7$robust_ci[-1,]

createSensitivityPlot_relativeMagnitudes(sensitivityresults7$robust_ci,
                                                    sensitivityresults7$orig_ci)
```
yielded the plot below.
![image](https://github.com/asheshrambachan/HonestDiD/assets/32146369/93284574-3bd0-43d6-8fed-9e015cbc5f13)

I'm not sure why the two final CIs have the same upper bound and the 4th and 5th from the right have the same lower bound? Experimenting with slightly different ub and lb generates the same behavior but for different CIs.

**Comment by jonathandroth** [comment]
Great. Likely because honestdid uses a discrete grid so the upper bounds
can be the same if the upper grid points are the same. You can also pass
num.gridpoints to change grid resolution

**Comment by jonathandroth** [comment]
If you are happy with the current grid resolution I don't think it's a
problem per we if two of the bounds match

**Comment by elsavoytas** [comment]
Agreed! Thanks for your help. I'm all set.
