### ISSUE TITLE
Use of alpha in construction of original confidence interval

### ISSUE THREAD

**Issue by poliquin** [asheshrambachan/HonestDiD#7]
Quick question... why does the following code for reproducing original confidence intervals use `qnorm(1 - alpha)` instead of `qnorm(1 - alpha/2)`?

https://github.com/asheshrambachan/HonestDiD/blob/c926b01ca613e2c04dda01f17880fc12f587933e/R/sensitivityresults.R#L388-L402

**Comment by asheshrambachan** [comment]
Thank you! It definitely should be `qnorm(1-alpha/2)` as opposed to `qnorm(1-alpha)`. I just pushed a commit to fix this.
