### ISSUE TITLE
Add documentation on how to import a regression from STata

### ISSUE THREAD

**Issue by jonathandroth** [asheshrambachan/HonestDiD#8]

**Comment by mcaceresb** [comment]
@jonathandroth LMK if you want me to write a snippet that does this? If you mean to export a result from Stata to file that can be read from R that's fairly easy using e.g. `readBin` (esp if you just want coef and vcov).

**Comment by jonathandroth** [comment]
I think I created this issue before the Stata package existed. It doesn't seem relevant now.
